align sslr toolkit with phyton and javascript.
toolkit is starting again now
but still not able to parse
add missing packages to fix 'NoClassDefFoundError: org/sonar/api/batch/fs/InputPath'